I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 265, in script
    python:
  File "renpy/common/00start.rpy", line 265, in script
    python:
  File "renpy/common/00start.rpy", line 269, in <module>
    renpy.call_in_new_context("_main_menu")
KeyError: u'_main_menu_screen'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/daniel/Documents/Sources/renpy/renpy-7.3.2-sdk/renpy/bootstrap.py", line 314, in bootstrap
    renpy.main.main()
  File "/home/daniel/Documents/Sources/renpy/renpy-7.3.2-sdk/renpy/main.py", line 529, in main
    run(restart)
  File "/home/daniel/Documents/Sources/renpy/renpy-7.3.2-sdk/renpy/main.py", line 139, in run
    renpy.execution.run_context(True)
  File "/home/daniel/Documents/Sources/renpy/renpy-7.3.2-sdk/renpy/execution.py", line 892, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 265, in script
    python:
  File "renpy/common/00start.rpy", line 265, in script
    python:
  File "/home/daniel/Documents/Sources/renpy/renpy-7.3.2-sdk/renpy/ast.py", line 912, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/daniel/Documents/Sources/renpy/renpy-7.3.2-sdk/renpy/python.py", line 2004, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/00start.rpy", line 269, in <module>
    renpy.call_in_new_context("_main_menu")
  File "/home/daniel/Documents/Sources/renpy/renpy-7.3.2-sdk/renpy/game.py", line 332, in call_in_new_context
    return renpy.execution.run_context(False)
  File "/home/daniel/Documents/Sources/renpy/renpy-7.3.2-sdk/renpy/execution.py", line 917, in run_context
    context.pop_all_dynamic()
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in script
    python hide:
  File "/home/daniel/Documents/Sources/renpy/renpy-7.3.2-sdk/renpy/execution.py", line 372, in pop_dynamic
    del store[k]
KeyError: u'_main_menu_screen'

Linux-4.19.0-8-amd64-x86_64-with-debian-10.3
Ren'Py 7.3.2.320
radiopulsarvn_predemo 1.0
Mon Mar 16 20:44:20 2020
